### ISSUE TITLE
Example fails for the array part

### ISSUE THREAD

**Issue by hadrien-toma** [binaryphile/y2s#4]
I am facing troubles with the array part of the example use case of `y2s`.
What I have:
- `ls`:
```sh
demo.yml  test.sh
```
- `cat demo.yml`:
```sh
myhash:
  one: 1
  two: 2
myarray:
  - zero
  - one
```
- `cat test.sh`:
```sh
#!/bin/bash

source y2s.bash
declare -A hash
yml2struct hash demo.yml

echo "begin"
echo "${hash[myhash]}"
echo "${hash[myhash.two]}"
echo "${hash[myarray]}"
echo "${hash[myarray.1]}"
echo "end"
```
- `./test.sh`:
```sh
begin
([one]="1" [two]="2" )
2
([0]="zero" )

end
```

**Comment by hadrien-toma** [comment]
Can't reproduce anymore, I don't know what happened. Seems to work as expected for now.

**Comment by binaryphile** [comment]
Best kind of bug report

**Comment by hadrien-toma** [comment]
Okay, I finally reached to reproduce: that was because I deleted the empty blank line at the end of `demo.yml`.

**Comment by binaryphile** [comment]
I'll need to add that to the limitations in the readme I guess.
