### ISSUE TITLE
What kind of YAML files are supported?

### ISSUE THREAD

**Issue by hadrien-toma** [binaryphile/y2s#5]
With this YAML file as `demo.yml` (taken from [here](http://www.yaml.org/spec/1.2/spec.html)):
```sh
--- !<tag:clarkevans.com,2002:invoice>
invoice: 34843
date   : 2001-01-23
bill-to: &id001
    given  : Chris
    family : Dumars
    address:
        lines: |
            458 Walkman Dr.
            Suite #292
        city    : Royal Oak
        state   : MI
        postal  : 48046
ship-to: *id001
product:
    - sku         : BL394D
      quantity    : 4
      description : Basketball
      price       : 450.00
    - sku         : BL4438H
      quantity    : 1
      description : Super Hoop
      price       : 2392.00
tax  : 251.42
total: 4443.52
comments:
    Late afternoon is best.
    Backup contact is Nancy
    Billsmer @ 338-4338.
```
This is what I execute:
```sh
source y2s.bash
declare -A hash
yml2struct hash demo.yml

echo "${hash[invoice]}"
```
But it outputs me a blank line :(.
I think the parser failed because of an unexpected format. May you explain which kind of YAML files are supported?

**Comment by binaryphile** [comment]
The section on limitations at the end of the readme details the
capabilities. Also read the link to YAY in the shouts-out section which
it's where I started from.

Problems I see:

- indents must all be two spaces apiece
- no references/addressing (& and *)
- no multiline values
- no formatted strings (|)

I would recommend cutting the file in halves until you find a small enough
piece which works as expected, then add pieces back in and fix them one at
a time.

**Comment by hadrien-toma** [comment]
Just wanted to say that: even if there are limitations, `y2s` looks really promising and already very usefull!
